# Tensors
Tensors are specialized data structures that are very similar to arrays and matrices.

Source: https://pytorch.org/tutorials/beginner/basics/tensor_tutorial.html

In [2]:
import torch
import numpy as np

## Initializing a Tensor
**Directly from Data**

In [6]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)
print(x_data.shape)

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])


**From a Numpy array**

In [9]:
np_array = np.array(data)
x_nap = torch.from_numpy(np_array)
print(x_nap)

tensor([[1, 2],
        [3, 4]])


**From another tensor**

In [11]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7552, 0.6127],
        [0.1551, 0.6378]]) 



**With random or constant values**

In [16]:
shape = (1,2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[[0.8867, 0.9129, 0.5837],
         [0.0387, 0.0353, 0.4561]]]) 

Ones Tensor: 
 tensor([[[1., 1., 1.],
         [1., 1., 1.]]]) 

Zeros Tensor: 
 tensor([[[0., 0., 0.],
         [0., 0., 0.]]]) 



## Attributes of a Tensor
Tensor attributes describe their shape, datatype, and device on which they are stored.

In [4]:
shape = (3, 4, )
tensor = torch.rand(shape)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Operations on Tensors
Tensor operations can be run on the GPU. But by default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using `.to` method. But copying large tensors across devices can be expensive in terms of time and memory.

In [3]:
is_cuda_available = torch.cuda.is_available()
print(f"Is CUDA available: {is_cuda_available}")

if is_cuda_available:
    tensor = tensor.to('cuda')
    print(f"Device tensor is stored on: {tensor.device}")

print(torch.device("mps"))


Is CUDA available: False
mps


In [9]:
tensor = torch.ones(4, 4)
print("First row: ", tensor[0])
print("First column: ", tensor[:, 0])
print("Last column: ", tensor[..., -1])
tensor[:,1] = 0 # Change all elements in the second column to 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column:  tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**Standard numpy-like indexing and slicing:**

In [13]:
tensor = tensor.to('mps')
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]], device='mps:0')


## Joining tensors

In [15]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]], device='mps:0')


**Arithmetic Operations**

In [28]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
print(y3)
torch.matmul(tensor, tensor.T, out=y3)

z1 = tensor * tensor
z2 = tensor.mul(tensor)

print(y1)
print(y2)
print(y3)

print(z1)
print(z2)

tensor([[0.0896, 0.2445, 0.9872, 0.0430],
        [0.5917, 0.7071, 0.6450, 0.6192],
        [0.4413, 0.3828, 0.2736, 0.0186],
        [0.4820, 0.8664, 0.2689, 0.5441]], device='mps:0')
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]], device='mps:0')
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]], device='mps:0')
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]], device='mps:0')
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]], device='mps:0')
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]], device='mps:0')


**Single-element tensors**

In [29]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


**In-place operations**

In [31]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]], device='mps:0') 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]], device='mps:0')


## Bridge with NumPy
### Tensor to NumPy array

In [38]:
t = torch.ones(5)
t = t.to('mps')
print(f"t: {t}")

# Can't run this on GPU
try: 
    n = t.numpy()
except Exception as e:
    print(e)
    
t = t.to('cpu')
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.], device='mps:0')
can't convert mps:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
n: [1. 1. 1. 1. 1.]


In [39]:
# Changes in the tensor reflect in the NumPy array.
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


## NumPy array to Tensor

In [47]:
n = np.ones(5)
t = torch.from_numpy(n)
print(f"n: {n}")
print(f"t: {t} {t.device}")


# Changes in the NumPy array reflect in the tensor.
np.add(n, 1, out=n)
print(f"n: {n}")
print(f"t: {t} {t.device}")

n: [1. 1. 1. 1. 1.]
t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64) cpu
n: [2. 2. 2. 2. 2.]
t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64) cpu
